language: java
before_script:
  - unset GEM_PATH GEM_HOME IRBRC
  - "export PATH=`pwd`/bin:$PATH"

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6

env:
  # disable cext
  global:
    - JAVA_OPTS="-server -Djruby.cext.enabled=false"
  matrix:
    - TARGET='test-extended'
    - TARGET='spec:ci_interpreted_via_env' RUBYSPEC_LANG_VER='1.8'
    - TARGET='spec:ci_interpreted_via_env' RUBYSPEC_LANG_VER='1.9'
    - TARGET='spec:ir'

matrix:
  fast_finish: true
  allow_failures:
    - env: TARGET='spec:ir'
    - jdk: oraclejdk8

branches:
  only:
    - krypt_syncup

before_install:
  - if [[ $TRAVIS_JDK_VERSION = 'oraclejdk8' ]]; then sudo apt-get update; sudo apt-get install oracle-java8-installer; else true; fi

script: "ant $TARGET"
install: /bin/true
